#!/usr/bin/env node
// Generates everything under src/generated/ from spec/openapi.json (see fetch-spec.mjs).
import { mkdir, readFile, writeFile } from 'node:fs/promises';
import { fileURLToPath } from 'node:url';
import { dirname, resolve } from 'node:path';
import openapiTS, { astToString } from 'openapi-typescript';
import { sha256 } from './lib/spec.mjs';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const specPath = resolve(root, 'spec/openapi.json');

let specText;
try {
  specText = await readFile(specPath, 'utf8');
} catch {
  console.error('error: spec/openapi.json is missing. Run `npm run fetch:spec` first.');
  process.exit(1);
}
const spec = JSON.parse(specText);
const specSha256 = sha256(specText);
await mkdir(resolve(root, 'src/generated'), { recursive: true });

const banner = `/**
 * DO NOT EDIT — generated by \`npm run generate\` from the live API description.
 * Spec: ${spec.info.title} ${spec.info.version} (sha256 ${specSha256})
 */

`;

const ast = await openapiTS(new URL(`file://${specPath}`), { alphabetize: true });
await writeFile(resolve(root, 'src/generated/schema.ts'), banner + astToString(ast));

const server = spec.servers?.[0];
if (!server?.url) {
  throw new Error('spec/openapi.json has no servers[0].url — cannot derive the default base URL');
}
await writeFile(
  resolve(root, 'src/generated/server.ts'),
  `${banner}/** ${server.description ?? 'Default server'} */
export const DEFAULT_BASE_URL = ${JSON.stringify(server.url)};

/** Value of \`info.version\` in the spec these types were generated from. It does not change when the content does. */
export const SPEC_VERSION = ${JSON.stringify(spec.info.version)};

/** SHA-256 of the exact spec bytes these types were generated from; this is what identifies a build. */
export const SPEC_SHA256 = ${JSON.stringify(specSha256)};
`,
);

const securityScheme = Object.values(spec.components?.securitySchemes ?? {}).find(
  (s) => s.type === 'apiKey' && s.in === 'header',
);
if (!securityScheme) {
  throw new Error('spec/openapi.json declares no apiKey-in-header security scheme');
}
await writeFile(
  resolve(root, 'src/generated/auth.ts'),
  `${banner}/** Header the Mangools API expects the account API key in. */
export const API_KEY_HEADER = ${JSON.stringify(securityScheme.name)};
`,
);

console.log(
  `generated src/generated/{schema,server,auth}.ts from ${spec.info.title} ${spec.info.version} ` +
    `(${Object.keys(spec.paths).length} paths, ${Object.keys(spec.components?.schemas ?? {}).length} schemas)`,
);
